$target = "d:\Bitflow_softwares\CNE\SVS_CNE\swami_vivekanand_school_of_nursing\app\downloads\page.tsx"

$lines = @(
'"use client";',
'',
'import { useState } from "react";',
'import {',
'  BookOpen,',
'  HelpCircle,',
'  File,',
'  Search,',
'  X,',
'  ExternalLink,',
'  Download,',
'  ChevronRight,',
'  FolderOpen,',
'  GraduationCap,',
'  FileText,',
'  ClipboardList,',
'} from "lucide-react";',
'import { Input } from "@/components/ui/input";',
'',
'const syllabi = [',
'  {',
'    id: "s1",',
'    year: "First Year",',
'    title: "First Year GNM Syllabus",',
'    type: "Drive Folder",',
'    date: "2024-01-15",',
'    category: "Syllabus",',
'    link: "https://drive.google.com/drive/folders/1uvwPuDSkNRUlF6oO50eWm-R0PF7DmYW2?usp=sharing",',
'  },',
'  {',
'    id: "s2",',
'    year: "Second Year",',
'    title: "Second Year GNM Syllabus",',
'    type: "Drive Folder",',
'    date: "2024-01-15",',
'    category: "Syllabus",',
'    link: "https://drive.google.com/drive/folders/1ibswo-fxNmj47Srk5Qls2pqcmrau834P?usp=sharing",',
'  },',
'  {',
'    id: "s3",',
'    year: "Third Year",',
'    title: "Third Year GNM Syllabus",',
'    type: "PDF",',
'    date: "2024-01-15",',
'    category: "Syllabus",',
'    link: null,',
'  },',
'  {',
'    id: "s4",',
'    year: "Internship",',
'    title: "Internship Guidelines & Logbook",',
'    type: "PDF",',
'    date: "2024-01-15",',
'    category: "Syllabus",',
'    link: null,',
'  },',
'];',
'',
'const questionBanks = [',
'  {',
'    id: "q1",',
'    year: "First Year",',
'    title: "First Year Question Bank",',
'    type: "PDF",',
'    date: "2023-12-10",',
'    category: "Question Bank",',
'    link: null,',
'  },',
'  {',
'    id: "q2",',
'    year: "Second Year",',
'    title: "Second Year Question Bank",',
'    type: "PDF",',
'    date: "2023-12-10",',
'    category: "Question Bank",',
'    link: null,',
'  },',
'  {',
'    id: "q3",',
'    year: "Third Year",',
'    title: "Third Year Question Bank",',
'    type: "PDF",',
'    date: "2023-12-10",',
'    category: "Question Bank",',
'    link: null,',
'  },',
'];',
'',
'const otherResources = [',
'  {',
'    id: "r1",',
'    title: "Admission Form 2026-27",',
'    type: "PDF",',
'    date: "2024-03-01",',
'    category: "Form",',
'    link: "https://drive.google.com/file/d/1m4c9Gpc1eAazJCNpbebRbhKeCNejM7j9/view",',
'  },',
'  {',
'    id: "r2",',
'    title: "Academic Calendar 2024",',
'    type: "PDF",',
'    date: "2024-01-01",',
'    category: "Calendar",',
'    link: null,',
'  },',
'  {',
'    id: "r3",',
'    title: "Student Handbook",',
'    type: "PDF",',
'    date: "2023-08-15",',
'    category: "Guide",',
'    link: null,',
'  },',
'  {',
'    id: "r4",',
'    title: "Scholarship Guidelines",',
'    type: "PDF",',
'    date: "2023-09-10",',
'    category: "Info",',
'    link: null,',
'  },',
'];',
'',
'const allFiles = [...syllabi, ...questionBanks, ...otherResources];',
'',
'type AccentType = "blue" | "green" | "violet";',
'',
'interface ResourceItem {',
'  id: string;',
'  title: string;',
'  type: string;',
'  date: string;',
'  category: string;',
'  link: string | null;',
'  year?: string;',
'}',
'',
'function ResourceCard({ item, accent }: { item: ResourceItem; accent: AccentType }) {',
'  const accentMap = {',
'    blue: {',
'      badge: "bg-blue-50 text-blue-700",',
'      icon: "bg-blue-50 text-blue-700",',
'      btn: "hover:text-blue-700 hover:border-blue-300",',
'    },',
'    green: {',
'      badge: "bg-emerald-50 text-emerald-700",',
'      icon: "bg-emerald-50 text-emerald-700",',
'      btn: "hover:text-emerald-700 hover:border-emerald-300",',
'    },',
'    violet: {',
'      badge: "bg-violet-50 text-violet-700",',
'      icon: "bg-violet-50 text-violet-700",',
'      btn: "hover:text-violet-700 hover:border-violet-300",',
'    },',
'  };',
'  const a = accentMap[accent];',
'  const Icon = accent === "blue" ? FileText : accent === "green" ? HelpCircle : File;',
'',
'  return (',
'    <div className="group flex flex-col bg-white rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-all duration-300 hover:-translate-y-0.5 overflow-hidden">',
'      <div className="p-5 flex-1">',
'        <div className="flex items-start justify-between mb-4">',
'          <div className={`p-2.5 rounded-xl ${a.icon}`}>',
'            <Icon className="h-5 w-5" />',
'          </div>',
'          <span className={`text-[11px] font-semibold uppercase tracking-wide px-2.5 py-1 rounded-full ${a.badge}`}>',
'            {item.year || item.category}',
'          </span>',
'        </div>',
'        <h3 className="font-semibold text-slate-900 text-sm leading-snug mb-1 min-h-[2.5rem]">',
'          {item.title}',
'        </h3>',
'        <p className="text-xs text-slate-400">{item.type}</p>',
'      </div>',
'      <div className="px-5 pb-5">',
'        <a',
'          href={item.link || "#"}',
'          target={item.link ? "_blank" : "_self"}',
'          rel="noopener noreferrer"',
'          className={`flex items-center justify-center gap-2 w-full py-2.5 rounded-xl border border-slate-200 text-slate-600 text-sm font-medium transition-colors ${a.btn} ${',
'            !item.link ? "opacity-50 cursor-not-allowed pointer-events-none" : ""',
'          }`}',
'        >',
'          {item.link ? (',
'            <>',
'              <ExternalLink className="h-4 w-4" />',
'              Open',
'            </>',
'          ) : (',
'            <>',
'              <Download className="h-4 w-4" />',
'              Coming Soon',
'            </>',
'          )}',
'        </a>',
'      </div>',
'    </div>',
'  );',
'}',
'',
'function SectionHeader({',
'  icon: Icon,',
'  label,',
'  title,',
'  description,',
'  id,',
'  accent,',
'}: {',
'  icon: React.ElementType;',
'  label: string;',
'  title: string;',
'  description: string;',
'  id: string;',
'  accent: AccentType;',
'}) {',
'  const accentColor: Record<AccentType, string> = {',
'    blue: "text-blue-700 bg-blue-50",',
'    green: "text-emerald-700 bg-emerald-50",',
'    violet: "text-violet-700 bg-violet-50",',
'  };',
'  return (',
'    <div id={id} className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-8">',
'      <div className="flex items-center gap-4">',
'        <div className={`p-3 rounded-xl ${accentColor[accent]}`}>',
'          <Icon className="h-6 w-6" />',
'        </div>',
'        <div>',
'          <p className="text-xs font-bold uppercase tracking-widest text-slate-400 mb-0.5">{label}</p>',
'          <h2 className="font-playfair font-bold text-2xl text-slate-900">{title}</h2>',
'        </div>',
'      </div>',
'      <p className="text-sm text-slate-500 max-w-sm">{description}</p>',
'    </div>',
'  );',
'}',
'',
'export default function StudentResourcesPage() {',
'  const [searchQuery, setSearchQuery] = useState("");',
'',
'  const filteredFiles = allFiles.filter(',
'    (f) =>',
'      f.title.toLowerCase().includes(searchQuery.toLowerCase()) ||',
'      ((f as ResourceItem).year || "").toLowerCase().includes(searchQuery.toLowerCase()) ||',
'      f.category.toLowerCase().includes(searchQuery.toLowerCase())',
'  );',
'',
'  const getAccent = (file: ResourceItem): AccentType => {',
'    if (syllabi.find((s) => s.id === file.id)) return "blue";',
'    if (questionBanks.find((q) => q.id === file.id)) return "green";',
'    return "violet";',
'  };',
'',
'  return (',
'    <div className="min-h-screen bg-slate-50">',
'      {/* HERO */}',
'      <section className="bg-white border-b border-slate-100 pt-28 pb-0 overflow-hidden">',
'        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">',
'          <div className="grid grid-cols-1 lg:grid-cols-2 gap-0 items-end">',
'            {/* Left */}',
'            <div className="py-12 lg:py-16 pr-0 lg:pr-16">',
'              <div className="flex items-center gap-3 mb-5">',
'                <div className="w-8 h-0.5 bg-blue-700"></div>',
'                <span className="text-blue-700 text-xs font-bold uppercase tracking-[0.2em]">Academic Portal</span>',
'              </div>',
'              <h1 className="font-playfair font-bold text-4xl sm:text-5xl lg:text-6xl text-slate-900 mb-5 leading-tight">',
'                Student<br />Resources',
'              </h1>',
'              <p className="text-slate-500 text-lg mb-8 max-w-md leading-relaxed">',
'                All your syllabi, question banks, forms, and academic materials — organized and always up to date.',
'              </p>',
'              <div className="relative max-w-md">',
'                <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400 pointer-events-none" />',
'                <Input',
'                  type="text"',
'                  placeholder="Search resources..."',
'                  className="pl-12 pr-10 py-3 rounded-2xl border-slate-200 bg-slate-50 focus:bg-white focus:border-blue-300 text-slate-900 placeholder:text-slate-400"',
'                  value={searchQuery}',
'                  onChange={(e) => setSearchQuery(e.target.value)}',
'                />',
'                {searchQuery && (',
'                  <button',
'                    onClick={() => setSearchQuery("")}',
'                    className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"',
'                  >',
'                    <X className="h-4 w-4" />',
'                  </button>',
'                )}',
'              </div>',
'              {!searchQuery && (',
'                <div className="flex flex-wrap gap-2 mt-6">',
'                  {[',
'                    { label: "Syllabus", href: "#syllabus" },',
'                    { label: "Question Banks", href: "#question-banks" },',
'                    { label: "Forms & More", href: "#resources" },',
'                  ].map((l) => (',
'                    <a',
'                      key={l.href}',
'                      href={l.href}',
'                      className="flex items-center gap-1 text-sm text-slate-600 border border-slate-200 rounded-full px-4 py-1.5 hover:border-blue-300 hover:text-blue-700 transition-colors"',
'                    >',
'                      {l.label}',
'                      <ChevronRight className="h-3.5 w-3.5" />',
'                    </a>',
'                  ))}',
'                </div>',
'              )}',
'            </div>',
'            {/* Right - 2x2 stat mosaic */}',
'            <div className="grid grid-cols-2 gap-px bg-slate-100 border-t border-l border-slate-100 rounded-tl-3xl overflow-hidden self-end">',
'              <div className="bg-blue-700 px-8 py-10 flex flex-col gap-2">',
'                <GraduationCap className="h-7 w-7 text-blue-200 mb-1" />',
'                <p className="text-4xl font-bold text-white">4</p>',
'                <p className="text-sm text-blue-200 font-medium">GNM Syllabi</p>',
'              </div>',
'              <div className="bg-slate-900 px-8 py-10 flex flex-col gap-2">',
'                <HelpCircle className="h-7 w-7 text-slate-400 mb-1" />',
'                <p className="text-4xl font-bold text-white">3</p>',
'                <p className="text-sm text-slate-400 font-medium">Question Banks</p>',
'              </div>',
'              <div className="bg-white px-8 py-10 flex flex-col gap-2 border-t border-slate-100">',
'                <FolderOpen className="h-7 w-7 text-violet-500 mb-1" />',
'                <p className="text-4xl font-bold text-slate-900">4+</p>',
'                <p className="text-sm text-slate-500 font-medium">Forms & Guides</p>',
'              </div>',
'              <div className="bg-slate-50 px-8 py-10 flex flex-col gap-2 border-t border-slate-100">',
'                <ClipboardList className="h-7 w-7 text-emerald-500 mb-1" />',
'                <p className="text-4xl font-bold text-slate-900">Free</p>',
'                <p className="text-sm text-slate-500 font-medium">Open Access</p>',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </section>',
'',
'      {/* CONTENT */}',
'      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-20">',
'        {searchQuery ? (',
'          <div>',
'            <div className="flex items-center justify-between mb-8">',
'              <h2 className="font-playfair font-bold text-2xl text-slate-900">Search Results</h2>',
'              <span className="text-sm text-slate-500">',
'                {filteredFiles.length} item{filteredFiles.length !== 1 && "s"} found',
'              </span>',
'            </div>',
'            {filteredFiles.length > 0 ? (',
'              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">',
'                {filteredFiles.map((f) => (',
'                  <ResourceCard key={f.id} item={f as ResourceItem} accent={getAccent(f as ResourceItem)} />',
'                ))}',
'              </div>',
'            ) : (',
'              <div className="text-center py-20 bg-white rounded-2xl border border-dashed border-slate-200">',
'                <Search className="h-10 w-10 text-slate-200 mx-auto mb-4" />',
'                <p className="font-semibold text-slate-700 mb-1">No results found</p>',
'                <p className="text-slate-400 text-sm">Try a different keyword.</p>',
'                <button onClick={() => setSearchQuery("")} className="text-blue-600 text-sm mt-3 underline">',
'                  Clear search',
'                </button>',
'              </div>',
'            )}',
'          </div>',
'        ) : (',
'          <>',
'            <section>',
'              <SectionHeader',
'                id="syllabus"',
'                icon={BookOpen}',
'                label="Curriculum"',
'                title="Course Syllabi"',
'                description="Detailed curriculum and course content for all academic years of the GNM programme."',
'                accent="blue"',
'              />',
'              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">',
'                {syllabi.map((f) => (',
'                  <ResourceCard key={f.id} item={f} accent="blue" />',
'                ))}',
'              </div>',
'            </section>',
'',
'            <section>',
'              <SectionHeader',
'                id="question-banks"',
'                icon={HelpCircle}',
'                label="Exam Prep"',
'                title="Question Banks"',
'                description="Previous year questions and practice sets to help you prepare for end-of-year examinations."',
'                accent="green"',
'              />',
'              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">',
'                {questionBanks.map((f) => (',
'                  <ResourceCard key={f.id} item={f} accent="green" />',
'                ))}',
'              </div>',
'            </section>',
'',
'            <section>',
'              <SectionHeader',
'                id="resources"',
'                icon={FolderOpen}',
'                label="Forms & Guides"',
'                title="Other Resources"',
'                description="Administrative forms, student handbooks, academic calendars, and scholarship information."',
'                accent="violet"',
'              />',
'              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">',
'                {otherResources.map((f) => (',
'                  <ResourceCard key={f.id} item={f} accent="violet" />',
'                ))}',
'              </div>',
'            </section>',
'          </>',
'        )}',
'',
'        {/* Notice */}',
'        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-7 flex flex-col sm:flex-row gap-5 items-start">',
'          <div className="bg-amber-100 p-3 rounded-xl shrink-0">',
'            <FileText className="h-6 w-6 text-amber-700" />',
'          </div>',
'          <div>',
'            <h3 className="font-semibold text-amber-900 mb-2">Access Instructions</h3>',
'            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-x-10 gap-y-1.5 text-amber-800 text-sm list-disc pl-4">',
'              <li>PDF files require Adobe Reader or any PDF viewer.</li>',
'              <li>Check back regularly — files are updated each academic year.</li>',
'              <li>Google Drive links open in a new tab; no sign-in required.</li>',
'              <li>For restricted files, contact the administrative office.</li>',
'            </ul>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',
'  );',
'}'
)

$lines -join "`n" | Set-Content $target -Encoding UTF8 -NoNewline
Write-Host "Done. Lines: $((Get-Content $target).Count)"
